USE vaadin;

CREATE TABLE `PERSON` (
  `ID`          BIGINT(20) NOT NULL,
  `ADDRESS`     VARCHAR(255) DEFAULT NULL,
  `AFFILIATION` VARCHAR(255) DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) DEFAULT NULL,
  `EMAIL`       VARCHAR(255) DEFAULT NULL,
  `FULLNAME`    VARCHAR(255) DEFAULT NULL,
  `PHONENUMBER` VARCHAR(255) DEFAULT NULL,
  `PROFESSION`  VARCHAR(255) DEFAULT NULL,
  `JOINEDDATE`  DATETIME     DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;


CREATE TABLE `SEQUENCE` (
  `SEQ_NAME`  VARCHAR(50) NOT NULL,
  `SEQ_COUNT` DECIMAL(38, 0) DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;